sonar.projectKey=s_unjani
sonar.projectName=s.unjani.ac.id
sonar.projectVersion=0.1.6

sonar.sourceEncoding=UTF-8
sonar.sources=src,scripts,views
sonar.exclusions=**/node_modules/**,public/**,**/*.min.js,**/.env,**/.env.*
sonar.html.file.suffixes=.html,.xhtml,.ejs

# This directory is a deployed source tree without Git metadata.
sonar.scm.disabled=true
